//! Build script: embeds `docs/adr/*.md` and `docs/analysis/*.md` in the library, generated from the folders so that nobody keeps a list of them
//! (`search` and `describe decisions` read the embedded copies, so they need no files at runtime; a new ADR used to have to be added to a Rust
//! list by hand and every parallel branch collided on it; ADR 2026-09-28-generated-bookkeeping).

use std::path::Path;

/// `(folder, generated file, constant)`: each folder's `*.md` files (except `README.md`) become `pub const <constant>: &[(&str, &str)]` of
/// `(file name, text)`, sorted by name.
const FOLDERS: &[(&str, &str, &str)] = &[("docs/adr", "adr_files.rs", "ADR_FILES"), ("docs/analysis", "analysis_files.rs", "ANALYSIS_FILES")];

fn main() {
    let root = std::env::var("CARGO_MANIFEST_DIR").expect("cargo sets CARGO_MANIFEST_DIR");
    let out = std::env::var("OUT_DIR").expect("cargo sets OUT_DIR");
    for (dir, file, constant) in FOLDERS {
        let mut names: Vec<String> = std::fs::read_dir(Path::new(&root).join(dir))
            .map(|rd| rd.flatten().map(|e| e.file_name().to_string_lossy().to_string()).filter(|n| n.ends_with(".md") && n != "README.md").collect())
            .unwrap_or_default();
        names.sort();
        let mut src = format!("/// Generated by build.rs from `{dir}`: `(file name, text)`.\npub const {constant}: &[(&str, &str)] = &[\n");
        for n in &names {
            src.push_str(&format!("    ({n:?}, include_str!(concat!(env!(\"CARGO_MANIFEST_DIR\"), \"/{dir}/{n}\"))),\n"));
        }
        src.push_str("];\n");
        std::fs::write(Path::new(&out).join(file), src).expect("write the generated registry");
        println!("cargo:rerun-if-changed={dir}");
    }
    println!("cargo:rerun-if-changed=build.rs");
}
