#!/usr/bin/env bash
# The exact steps CI runs (.github/workflows/ci.yml). Run before pushing; green here = green there
# (on this platform). Usage: scripts/ci.sh [stage ...]      (no stage = all of them, in this order)
#
#   fmt  clippy  tests  benches  headless-tree  headless-build  headless-clippy  headless-tests  external-client  video  pytools
#   games  direct3d  (not in the default list: `tests` covers them; they are what the hosted workflow runs instead of `tests` in two cases, see each one)
#
# Tests run under cargo-nextest when it is installed (ADR 2026-10-10-ci-runs-the-tests-under-nextest), in ONE run on all cores, each test in its own process:
#   * suites listed under "serial_suites" in docs/features.json (real-time UDP, spawned servers) form a nextest test group with max-threads = 1 whose tests take
#     every slot: one at a time with nothing else running, as before (the config is generated from the index at run time, so the list cannot drift);
#   * doctests, which nextest cannot run, in `cargo test --doc`.
# Without nextest (or with RED_CI_NO_NEXTEST=1) the old three cargo-test runs are used: parallel group, doctests, serial group one test at a time.
# RED_CI_SERIAL_ALL=1 runs everything one test at a time. RED_CI_PARTITION=hash:K/N runs the K-th of N shards (doctests on shard 1 only).
set -euo pipefail
cd "$(dirname "$0")/.."
# Find cargo the way scripts/dev does, so this works from a shell that was started without it on PATH.
for f in "$HOME/.local/toolchain/env.sh" "$HOME/.cargo/env"; do [ -f "$f" ] && . "$f"; done
case ":$PATH:" in *":$HOME/.cargo/bin:"*) ;; *) PATH="$HOME/.cargo/bin:$PATH" ;; esac
export PATH CARGO_TERM_COLOR="${CARGO_TERM_COLOR:-never}"

# The serial suites, read from the index without needing a built binary.
serial_suites() {
  tr -d '\n' < docs/features.json | grep -o '"serial_suites": *\[[^]]*\]' | grep -oE '"[a-z0-9_]+"' | tr -d '"' | grep -vx serial_suites || true
}

use_nextest() { [ "${RED_CI_NO_NEXTEST:-0}" != "1" ] && cargo nextest --version >/dev/null 2>&1; }

# The nextest configuration, written from the index under target/ each run: the serial suites as one test group that runs one test at a time.
nextest_config() {
  local f="target/nextest-ci.toml" filter="" s
  mkdir -p target
  for s in $(serial_suites); do filter+="${filter:+ | }binary(=$s)"; done
  {
    echo "# Generated by scripts/ci.sh from docs/features.json (serial_suites); do not edit."
    echo "[test-groups]"
    echo "serial-suites = { max-threads = 1 }"
    echo "[profile.default]"
    echo "fail-fast = false"
    echo "status-level = \"fail\""
    echo "final-status-level = \"slow\""
    if [ -n "$filter" ]; then
      echo "[[profile.default.overrides]]"
      echo "filter = '$filter'"
      echo "test-group = 'serial-suites'"
      # A real-time suite takes every slot: nothing else runs while it does. They time packets and physics in real time, and sharing the machine failed them
      # (net_e2e loss/latency on hosted CI, net_e2e reconnect locally, with two slots reserved; docs/analysis/2026-10-10-ci-wall-clock.md).
      echo "threads-required = 'num-test-threads'"
    fi
  } > "$f"
  echo "$f"
}

# run_tests [cargo flags...]: the whole suite for one feature set.
run_tests() {
  if use_nextest; then
    local cfg part=() threads=()
    cfg="$(nextest_config)"
    [ -n "${RED_CI_PARTITION:-}" ] && part=(--partition "$RED_CI_PARTITION")
    [ "${RED_CI_SERIAL_ALL:-0}" = "1" ] && threads=(--test-threads 1)
    echo "-- nextest: lib, bins, every suite; serial suites one at a time ($(serial_suites | grep -c .) suite(s), group serial-suites)${part[0]:+, shard ${RED_CI_PARTITION}}"
    cargo nextest run --locked --config-file "$cfg" --no-fail-fast "$@" --lib --bins --tests ${part[@]+"${part[@]}"} ${threads[@]+"${threads[@]}"}
    if [ -z "${RED_CI_PARTITION:-}" ] || [ "${RED_CI_PARTITION#*:}" = "1/${RED_CI_PARTITION#*/}" ]; then
      echo "-- doctests"
      cargo test --locked --no-fail-fast "$@" --doc
    fi
    return
  fi
  if [ "${RED_CI_NO_NEXTEST:-0}" = "1" ]; then echo "-- RED_CI_NO_NEXTEST=1: the old three cargo-test runs"; else echo "-- cargo-nextest is not installed (cargo install cargo-nextest --locked): the old three cargo-test runs"; fi
  local serial parallel=() serial_args=() t name
  serial="$(serial_suites)"
  for t in tests/*.rs; do
    name="$(basename "$t" .rs)"
    if [ "${RED_CI_SERIAL_ALL:-0}" != "1" ] && ! grep -qx "$name" <<<"$serial"; then parallel+=(--test "$name"); else serial_args+=(--test "$name"); fi
  done
  echo "-- parallel group: lib, bins, ${#parallel[@]} suite flag(s)"
  cargo test --locked --no-fail-fast "$@" --lib --bins ${parallel[@]+"${parallel[@]}"}
  echo "-- doctests"
  cargo test --locked --no-fail-fast "$@" --doc
  if [ ${#serial_args[@]} -gt 0 ]; then
    echo "-- serial group (one test at a time, real-time networking)"
    RUST_TEST_THREADS=1 cargo test --locked --no-fail-fast "$@" "${serial_args[@]}"
  fi
}

stage_fmt() { echo "== rustfmt (rustfmt.toml is the style) =="; cargo fmt --check; }
stage_clippy() { echo "== clippy (warnings are errors) =="; cargo clippy --locked --all-targets -- -D warnings; }
stage_tests() { echo "== tests (lib, integration, doctests) =="; run_tests; }
# "The benches compile" is a type-check question: `check` answers it in seconds, where `bench --no-run` builds the whole engine optimised (measured: 475 s of
# a 1167 s local run, all of it for binaries nobody runs). RED_CI_BUILD_BENCHES=1 restores the full build.
stage_benches() {
  echo "== benches compile =="
  if [ "${RED_CI_BUILD_BENCHES:-0}" = "1" ]; then cargo bench --locked --no-run; else cargo check --locked --benches; fi
}
stage_headless_tree() {
  echo "== headless server: no graphics, audio or MCP crates in the dependency tree =="
  # The tree is captured first, then searched: piped straight into grep, a *failing* `cargo tree` (a stale Cargo.lock under
  # --locked, a broken registry) matched nothing and the stage passed with nothing checked.
  local tree
  if ! tree="$(cargo tree --locked --no-default-features -e normal --prefix none)"; then
    echo "cargo tree failed: the headless dependency tree could not be checked (a stale Cargo.lock? run cargo update -p <crate> or regenerate it)"; exit 1
  fi
  if [ -z "$tree" ]; then echo "cargo tree printed nothing: the dependency check ran on an empty tree"; exit 1; fi
  if grep -E '^(wgpu|winit|softbuffer|rodio|cpal|alsa|pollster|ffmpeg-sidecar|naga|ash|rmcp|schemars) ' <<<"$tree"; then
    echo "a graphics, audio or MCP-adapter crate leaked into the headless build"; exit 1
  fi
  echo "$(grep -c . <<<"$tree") crates checked, no graphics, audio or MCP crate among them"
}
stage_headless_build() {
  echo "== headless server builds without the gfx feature =="
  # The question here is "do the binaries build and link without gfx", which the dev profile answers from the artifacts `headless-tests` builds anyway, in CI too
  # (ADR 2026-10-10-ci-builds-the-headless-server-in-the-dev-profile): the LTO release build of these binaries is release.yml's (built and smoke-tested) and the
  # container image's (the `docker` job builds it on every change to what the image is made of). RED_CI_RELEASE=1 asks for the release build here.
  if [ "${RED_CI_RELEASE:-0}" = "1" ]; then
    cargo build --locked --release --no-default-features --bin red_server --bin red_bot
  else
    cargo build --locked --no-default-features --bin red_server --bin red_bot
  fi
}
stage_headless_clippy() { echo "== headless clippy =="; cargo clippy --locked --no-default-features --all-targets -- -D warnings; }
stage_headless_tests() { echo "== headless tests (incl. real-UDP server tests) =="; run_tests --no-default-features; }
# A game outside the engine crate that uses only the public client layer (`red_engine2::app`, ADR 0043): if the API breaks it, CI says so.
# Its presentation test renders offscreen; a runner with no GPU adapter at all sets RED_OFFSCREEN_OPTIONAL=1 to skip just that check.
# Every example crate that is its own workspace has its own Cargo.lock; it must follow the engine's dependencies or `--locked` refuses it with a message that does not say so.
# Seconds, and the commonest reason a dependency change fails CI: so it is its own stage and runs FIRST (measured on PR #44: found by the last stage of a 14-minute job).
check_example_locks() {
  local manifest
  for manifest in examples/external/*/Cargo.toml; do
    # Only crates that use the engine and keep a lock of their own (a standalone experiment that does not use the engine has neither to fall behind).
    [ -f "$manifest" ] && [ -f "$(dirname "$manifest")/Cargo.lock" ] && grep -q '^red_engine2' "$manifest" || continue
    if ! cargo metadata --locked --manifest-path "$manifest" --format-version 1 >/dev/null 2>&1; then
      echo "$(dirname "$manifest")/Cargo.lock is behind the engine's dependencies: run"
      echo "  cargo metadata --manifest-path $manifest --format-version 1 >/dev/null"
      echo "and commit the updated lock."; exit 1
    fi
  done
}
stage_lockfiles() { echo "== example crates' lock files follow the engine's dependencies =="; check_example_locks; echo "ok"; }
stage_external_client() {
  echo "== external custom client (examples/external/topdown_switch) =="
  check_example_locks
  cargo clippy --locked --manifest-path examples/external/topdown_switch/Cargo.toml --all-targets -- -D warnings
  cargo test --locked --manifest-path examples/external/topdown_switch/Cargo.toml
}

# Killchain is a game on the engine's public API (games/killchain, ADR 2026-10-09-killchain-is-a-game-crate-on-the-public-engine-api): a workspace member that is not a default member, so
# the engine's own stages never compile it and the headless build never sees its graphics crates. If an engine API change breaks the game, this stage says so.
stage_killchain() {
  echo "== Killchain (games/killchain) builds, lints and tests against the engine's public API =="
  cargo clippy --locked -p killchain --all-targets -- -D warnings
  cargo test --locked -p killchain
}

# The optional export capability stays buildable and lint clean: MP4 export (`video`, ffmpeg-sidecar) is not in the default build (ADR 2026-10-07-tooling-dependencies-are-optional-features).
stage_video() { echo "== optional MP4 export builds (feature video) =="; cargo clippy --locked --bins --lib --features video -- -D warnings; }

# The Python tools (launchpad, Idea Forge, the process supervisor, the publisher) on this platform's interpreter, with no Rust build: path handling, quoting, subprocess and git behaviour
# differ between Linux and Windows, and the hosted `python-tools` job runs this stage on both whenever one of them changes (ADR 2026-10-09-ci-runs-the-python-tools-on-windows-when-they-change).
# `tests` runs the same files through their `tests/*.rs` wrappers; this is the cheap way to run just them.
stage_pytools() {
  echo "== python tools (this platform's interpreter, no Rust build) =="
  local py="" p t
  for p in python3 python; do
    if command -v "$p" >/dev/null 2>&1 && "$p" --version >/dev/null 2>&1; then py="$p"; break; fi
  done
  if [ -z "$py" ]; then echo "python is not installed: the tool tests cannot run"; exit 1; fi
  "$py" --version
  "$py" -m compileall -q scripts mcp_server.py
  for t in scripts/test_*.py; do
    echo "-- $t"
    "$py" "$t"
  done
  echo "-- scripts/publish_games.py check"
  "$py" scripts/publish_games.py check
}

# The Windows leg of a pull request (ADR 2026-10-10-windows-ci-on-pull-requests-is-build-and-direct3d): every binary builds and links on Windows (cargo builds all of them to give the
# integration tests their CARGO_BIN_EXE_* paths, so this compiles the engine once, not twice), naga's HLSL checks run, and `shadow_render` creates a real Direct3D device on the
# hosted runner's adapter (WARP) and builds the renderer's world, post and ocean pipelines through Microsoft's shader compiler: the one thing only Windows can say. The full
# suite on Windows runs on pushes to main. `shadow_render` skips itself on a machine with no adapter, so on Windows this stage refuses to count a skip as a pass.
stage_direct3d() {
  echo "== Windows: every binary builds and links; shaders compile through Direct3D =="
  cargo test --locked --no-fail-fast --test shader_validation
  local out
  out="$(cargo test --locked --test shadow_render -- --nocapture 2>&1)" || { echo "$out"; exit 1; }
  grep -E '^(test |test result)' <<<"$out" || true
  if [ "${RED_DIRECT3D_REQUIRED:-0}" = "1" ] && grep -q "no GPU adapter on this machine" <<<"$out"; then
    echo "shadow_render found no GPU adapter: Direct3D was not exercised, so this run proves nothing about it"; exit 1
  fi
}

# A pull request that only adds or edits generated games (examples/2d, examples/3d, docs/analysis/idea-forge: the `games_only` output of the workflow's `changes` job) runs the tests that read
# that data and nothing else: every game must verify (games2d, games3d), keep well-formed checks, and the documents must stay fresh and linked. Not a replacement for `tests`.
stage_games() {
  echo "== generated games: the suites that read examples/2d, examples/3d and the notes =="
  cargo test --locked --no-fail-fast --test games2d --test games3d --test checks_wellformed --test examples_validate --test docs_fresh --test repo_hygiene
}

stages=("$@")
# Cheapest, most-likely-to-fail first: formatting, the lock files and the headless dependency tree take seconds; the long stages come after them.
[ ${#stages[@]} -gt 0 ] || stages=(fmt lockfiles headless-tree clippy tests benches headless-build headless-clippy headless-tests external-client killchain video pytools)
# Every stage is timed, and the table at the end says where the minutes went (the first thing to read when CI feels slow).
timings=()
t_all=$SECONDS
for s in "${stages[@]}"; do
  fn="stage_${s//-/_}"
  if ! declare -F "$fn" >/dev/null; then echo "ci.sh: unknown stage '$s'" >&2; exit 2; fi
  t0=$SECONDS
  "$fn"
  timings+=("$(printf '%5ds  %s' $((SECONDS - t0)) "$s")")
done
echo "-- stage times"
printf '   %s\n' "${timings[@]}"
echo "CI OK ($((SECONDS - t_all)) s)"
