#!/usr/bin/env python3
"""Report (and with --apply, delete) build leftovers that cost disk and nothing else: incremental-compilation directories nobody has used for N days.

A target directory grows without bound on a machine that builds many test binaries: one `incremental/<crate>-<hash>` directory of hundreds of megabytes per binary per variant,
long after the code that made it changed (measured here: 22 GB of 59 GB). When the disk fills, builds fail in confusing ways. Everything deleted is regenerated by the next build of
that unit, so nothing here can make a result wrong; only the *next* build of an untouched unit is slower, which is why only directories idle for `--days` (default 14) are chosen.

    python3 scripts/prune_target.py                      # what is there and what could go (nothing is deleted)
    python3 scripts/prune_target.py --apply --days 7     # delete incremental dirs idle for a week
"""
import argparse, os, pathlib, shutil, time


def du(path):
    total = 0
    for r, _, files in os.walk(path, onerror=lambda e: None):
        for f in files:
            try:
                total += os.lstat(os.path.join(r, f)).st_size
            except OSError:
                pass
    return total


def newest(path):
    best = 0.0
    for r, _, files in os.walk(path, onerror=lambda e: None):
        for f in files:
            try:
                best = max(best, os.lstat(os.path.join(r, f)).st_mtime)
            except OSError:
                pass
    return best


def main():
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--target", default=os.environ.get("CARGO_TARGET_DIR") or str(pathlib.Path(__file__).resolve().parent.parent / "target"))
    ap.add_argument("--days", type=float, default=14.0)
    ap.add_argument("--apply", action="store_true")
    a = ap.parse_args()
    target = pathlib.Path(a.target)
    if not target.is_dir():
        raise SystemExit(f"{target} does not exist")
    cutoff = time.time() - a.days * 86400
    print(f"{target}: " + ", ".join(f"{e.name} {du(e.path) / 1e9:.1f} GB" for e in sorted(os.scandir(target), key=lambda e: e.name) if e.is_dir() and du(e.path) > 5e7))
    idle, kept, total_idle = [], 0, 0
    for inc in target.glob("**/incremental"):
        if not inc.is_dir():
            continue
        for d in os.scandir(inc):
            if not d.is_dir():
                continue
            if newest(d.path) < cutoff:
                size = du(d.path)
                idle.append((d.path, size))
                total_idle += size
            else:
                kept += 1
    print(f"incremental directories idle for {a.days:g}+ days: {len(idle)} ({total_idle / 1e9:.1f} GB); recently used, kept: {kept}")
    for path, size in sorted(idle, key=lambda x: -x[1])[:5]:
        print(f"  {size / 1e6:8.0f} MB  {path.replace(str(target) + '/', '')}")
    if a.apply:
        for path, _ in idle:
            shutil.rmtree(path, ignore_errors=True)
        print(f"deleted {len(idle)} directories, {total_idle / 1e9:.1f} GB (rebuilt on demand)")
    elif idle:
        print("nothing deleted: add --apply to delete them")


if __name__ == "__main__":
    main()
