//! Map-authoring and analysis tools, exposed as `red_engine2` subcommands (see `src/main.rs`
//! and `AGENTS.md`). Everything here works on the same [`world::MapWorld`] — a scene flattened
//! into world-space items plus the *engine's own* collision/ground data — so the tools answer
//! questions about what the live game will actually do.

/// The message every render-dependent command returns in a build without the `gfx` feature.
#[cfg(not(target_arch = "wasm32"))]
pub const NO_GFX: &str = "this build has no renderer (built with --no-default-features); rebuild with `cargo build --release` (feature `gfx`, on by default) to use frame/tour/render/storyboard, catalog --sheet and golden-view checks";

/// What `render` (MP4 export) says in a build without the `video` feature.
#[cfg(not(target_arch = "wasm32"))]
pub const NO_VIDEO: &str = "this build cannot export MP4 (cargo feature `video`, not in the default build): rebuild with `cargo build --release --features video` and have ffmpeg on PATH. PNG output needs neither: `frame`, `tour`, `storyboard`, `ui-shot`";

#[cfg(not(target_arch = "wasm32"))]
pub mod adr;
#[cfg(not(target_arch = "wasm32"))]
pub mod affected;
#[cfg(not(target_arch = "wasm32"))]
pub mod agent_trace;
#[cfg(not(target_arch = "wasm32"))]
pub mod analysis;
#[cfg(not(target_arch = "wasm32"))]
pub mod audio;
#[cfg(not(target_arch = "wasm32"))]
pub mod audio_checks;
#[cfg(not(target_arch = "wasm32"))]
pub mod blueprint;
#[cfg(not(target_arch = "wasm32"))]
pub mod catalog;
#[cfg(not(target_arch = "wasm32"))]
pub mod check_schema;
#[cfg(not(target_arch = "wasm32"))]
pub mod context;
#[cfg(not(target_arch = "wasm32"))]
pub mod describe;
#[cfg(not(target_arch = "wasm32"))]
pub mod diff;
pub mod doc_claims;
#[cfg(not(target_arch = "wasm32"))]
pub mod doctor;
#[cfg(not(target_arch = "wasm32"))]
pub mod edit;
#[cfg(not(target_arch = "wasm32"))]
pub mod envelope;
#[cfg(not(target_arch = "wasm32"))]
pub mod features;
#[cfg(not(target_arch = "wasm32"))]
pub mod flora_sheet;
pub mod font;
#[cfg(not(target_arch = "wasm32"))]
pub mod game;
#[cfg(not(target_arch = "wasm32"))]
pub mod game2d;
#[cfg(not(target_arch = "wasm32"))]
pub mod gamepublish;
#[cfg(not(target_arch = "wasm32"))]
pub mod gen;
#[cfg(not(target_arch = "wasm32"))]
pub mod gitscope;
#[cfg(not(target_arch = "wasm32"))]
pub mod inspect;
#[cfg(not(target_arch = "wasm32"))]
pub mod lint;
#[cfg(not(target_arch = "wasm32"))]
pub mod nav;
#[cfg(not(target_arch = "wasm32"))]
pub mod nettest;
#[cfg(not(target_arch = "wasm32"))]
pub mod newgame;
#[cfg(not(target_arch = "wasm32"))]
pub mod package;
#[cfg(not(target_arch = "wasm32"))]
pub mod patch;
#[cfg(not(target_arch = "wasm32"))]
pub mod pathing;
#[cfg(not(target_arch = "wasm32"))]
pub mod pe;
#[cfg(not(target_arch = "wasm32"))]
pub mod perf;
#[cfg(not(target_arch = "wasm32"))]
pub mod plan;
#[cfg(not(target_arch = "wasm32"))]
pub mod portmap;
#[cfg(not(target_arch = "wasm32"))]
pub mod preflight;
#[cfg(not(target_arch = "wasm32"))]
pub mod procgen_map;
#[cfg(not(target_arch = "wasm32"))]
pub mod propose;
#[cfg(not(target_arch = "wasm32"))]
pub mod publish_check;
#[cfg(not(target_arch = "wasm32"))]
pub mod racetest;
#[cfg(not(target_arch = "wasm32"))]
pub mod racetrack;
#[cfg(not(target_arch = "wasm32"))]
pub mod reach;
#[cfg(not(target_arch = "wasm32"))]
pub mod recipes;
#[cfg(not(target_arch = "wasm32"))]
pub mod search;
#[cfg(not(target_arch = "wasm32"))]
pub mod servers;
#[cfg(not(target_arch = "wasm32"))]
pub mod sheet;
#[cfg(not(target_arch = "wasm32"))]
pub mod shots;
#[cfg(not(target_arch = "wasm32"))]
pub mod sight;
#[cfg(not(target_arch = "wasm32"))]
pub mod simrun;
#[cfg(not(target_arch = "wasm32"))]
pub mod status;
#[cfg(not(target_arch = "wasm32"))]
pub mod symbols;
#[cfg(not(target_arch = "wasm32"))]
pub mod upgrade;
#[cfg(not(target_arch = "wasm32"))]
pub mod verify;
#[cfg(not(target_arch = "wasm32"))]
pub mod walk;
#[cfg(not(target_arch = "wasm32"))]
pub mod world;
